### ISSUE TITLE
skate.js.org being rendered with no styles

### ISSUE THREAD

**Issue by joeljuca** [skatejs/skatejs.github.io#11]
Is it normal?

![captura de tela 2016-11-04 13 17 15](https://cloud.githubusercontent.com/assets/673884/20013233/2c6db03a-a291-11e6-8116-2014954f6d0a.png)

**Comment by treshugart** [comment]
That [should have been fixed](https://github.com/skatejs/web-components/blob/94c6c891ba2d75f034864ed8efc7daba52628774/src/fix/safari.js) but seems to have reappeared for some reason. Turns out Safari released a broken shadow DOM implementation (knowingly, unfortunately). See https://bugs.webkit.org/show_bug.cgi?id=160331 for more details. Fix is in tech preview.

I'll leave this open to address by forcing the polymer polyfill but that will take a little bit of work.

**Comment by treshugart** [comment]
Just reported in Skate issues: https://github.com/skatejs/skatejs/issues/924.

**Comment by Hotell** [comment]
since safari 10.2 fixes shadowdom implementation, this is no longer an issue.
