### ISSUE TITLE
Broken in Chrome 53

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs.github.io#6]
For some reason, native Shadow DOM v1 has broken the navigation and the todo list example.

**Comment by Hotell** [comment]
it hasn't IMHO. the implementation is bad. 

you cannot just apply `{display:none}` on LightDOM, in native implementation it needs to be "hidden" by [`::slotted()` selector](https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#stylinglightdom)

There few more bugs though:
- `.map` doesn't work because https://github.com/skatejs/skatejs/issues/830
- `items` is a `NodeList` not an `Array` so it needs to be converted to real Array

I've fixed it:

https://plnkr.co/edit/4rm0kJYhBTvK3un6P5VY?p=preview

should I create PR?

**Comment by treshugart** [comment]
@Hotell I actually created a working branch fixing most of this yesterday. Instead of using `::slotted`, I've opted to wrap the slot in a hidden `<div />` to reduce the amount of CSS I'd need to write. We have https://gist.github.com/treshugart/b609f856888bef7fbccafe51356171d2, though, but things aren't in JSS.

**Comment by treshugart** [comment]
I've removed the todo list example for now until https://github.com/skatejs/skatejs/issues/863 is resolved. That also negates the need for a `<slot />` just to trigger a re-render with child node info. Map now works (PR was merged and released) and the `slot()` prop type fixes the `NodeList` problem.
